name: dlaroslin
description: "Oficjalna aplikacja sklepu Dlaroslin. Zakupy ro\u015Blin doniczkowych,\
  \ nawozy, porady i inspiracje."
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.7.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0
  url_launcher: ^6.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  connectivity_plus: ^6.0.3
  webview_flutter_android: ^4.7.0
dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
flutter_launcher_icons:
  android: true
  image_path: assets/images/logo.png
